# -*- coding: utf-8 -*-
"""input.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17IXNJ9Rii6Knl1AUSls8x8Ac2Q2k_ltp
"""

import numpy as np
import bisection
def f(x):
  w0 = 15
  L = 3
  E = 70
  I = 52.9*(10^-6)
  pi = np.pi
  return ((w0*L)/(3*E*I*(pi**4)))*((48*(L**3)*np.cos((pi*x)/(2*L)))-(48*(L**3
  ))+(3*(pi**3)*L*(x**2))-((pi**3)*(x**3)))
# Initial values assumed
x_L = -4;   x_R = 4
y = open("bisection.txt", 'w')  
solution, no_iterations = bisection.bisection(f, x_L, x_R, eps=1.0e-6)
print('Number of iteration: {:d}'.format(no_iterations), file = y)
print('A solution is: {:f}'.format(solution), file = y)
y.close()

